[package]
name = "jelly"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"

log = "0.4"
env_logger = "0.10"
paste = "1.0.15"

[build-dependencies]
prost-build = "0.14.1"
